version: '3'

services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/manage.py makemigrations --noinput && python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A youtubeapp worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A youtubeapp beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: